### ISSUE TITLE
Error on running getstorybook

### ISSUE THREAD

**Issue by sonicviz** [kadirahq/react-storybook#430] opened 2016-09-06 03:01 UTC
Hi,
I have a test meteor react todo project which runs fine, and wanted to add storybook to learn it while prototyping some new UI components.

Tried the recommended setup sequence but gets fails on:

G:\Meteor Projects\Meteor 1.4\rubix-meteor-todolist>getstorybook 

 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "Meteor" app. ✓
 • Preparing to install NPM dependencies. ✓
 • Installing NPM dependencies. ✖

     An error occured while running `npm install`.

**Comment by mnmtanish** [comment] 2016-09-06 03:05
Hi,
Is there an npm-debug.log file in your project directory? It may have more information on why `npm install` failed.

**Comment by sonicviz** [comment] 2016-09-06 03:21
no

**Comment by mnmtanish** [comment] 2016-09-06 04:02
Can you send me the link to the todo list repo

**Comment by sonicviz** [comment] 2016-09-06 04:13
No I can't because it's a paid template: https://wrapbootstrap.com/theme/rubix-reactjs-powered-admin-template-WB09498FH 

Cheap, but paid nonetheless. The project was the meteor react todo example they have as a sample and also as a tutorial (different from MDG guide react todo) 
Was working fine, added storybook and broke it badly!

**Comment by arunoda** [comment] 2016-09-06 08:11
We need to see what's actually breaking here. It's hard to say without seeing any error info.
Anyway, try to use our [Slow Start Guide](https://getstorybook.io/docs/basics/slow-start-guide).

**Comment by arunoda** [comment] 2016-09-06 08:14
May be this is a related issue: https://github.com/kadirahq/react-storybook/issues/423

**Comment by sonicviz** [comment] 2016-09-06 08:55
I tried both guides, same error. 

I'd email support@sketchpixy.com and ask them for a free copy of rubix. They'd probably give you one considering what you do and the reported bug. If they do try it with the example meteor react todo project. That's how I got the error.

**Comment by darthtrevino** [comment] 2016-09-07 18:04
I ran into this issue, but it's because my machine was configured to use a Sinopia proxy instead of the global NPM registry directly.

**Comment by arunoda** [comment] 2016-09-15 06:19
I hope we can close this now.

**Closed by arunoda** 2016-09-15 06:19 UTC
Labels: discuss

**Comment by sonicviz** [comment] 2016-09-15 09:13
Don't know, afaik it's still there!

**Comment by arunoda** [comment] 2016-09-16 00:51
Try this: https://github.com/kadirahq/react-storybook/issues/122#issuecomment-216820405

**Comment by Nesciosquid** [comment] 2016-10-10 16:03
I am running into this on both my Win7 and Win10 machines, regardless of which repo I try to install to.

**Comment by robcaldecott** [comment] 2016-11-30 13:05
The problem is spawnSync, used in lib/helpers.js. If you change the npm command to npm.cmd then it works.

```javascript
exports.installDeps = function (options) {
  var done = exports.commandLog('Preparing to install dependencies');
  done();
  console.log();

  var result;
  if (options.useYarn) {
    result = spawnSync('yarn', { stdio: 'inherit' });
  } else {
    result = spawnSync('npm.cmd', ['install'], { stdio: 'inherit' });
  }

  done = exports.commandLog('Installing dependencies');
  if (result.status !== 0) {
    done('An error occurred while installing dependencies.');
    process.exit(1);
  }
  done();
};
```

**Comment by UsulPro** [comment] 2016-11-30 13:38
Looks like it's same issue #628

I changed it to 
`result = shell.exec('npm install');`
and it works as well!

**Comment by alebrozzo** [comment] 2017-01-12 13:16
Just doing npm i after the original failing message
`An error occured while running 'npm install'`
worked for me.

**Comment by arunoda** [comment] 2017-01-12 17:27
@alebrozzo could you check the errors on `npm.log` or similar file in the root of your app.

**Comment by NitroBAY** [comment] 2017-02-28 18:26
The problem is still here

**Comment by zhouchengcom** [comment] 2017-03-08 03:39
Looks like it's the same issue #628

I changed it to  Absolute path

spawnSync('C:/Users/Administrator/AppData/Roaming/npm/npm.cmd'
and it works as well!

**Comment by veerjainATgmail** [comment] 2017-06-17 05:23
was getting the above error.. later I tried, 

npm i -g @storybook/cli
cd my-react-app
getstorybook

it worked..

**Comment by claym** [comment] 2017-07-01 21:49
changing it to npm.cmd seems to have addressed it for me as well.

**Comment by UsulPro** [comment] 2017-07-01 22:19
@claym it should be solved in v3.x 
what version of Storybook do you use?

**Comment by claym** [comment] 2017-07-02 00:21
well, today i installed via npm install --global getstorybook which seems to be 1.7.0

but apparently that's the wrong package to use :D 

I was following a tutorial. Seems storybook/cli works!

So, nevermind!

**Comment by dcu-sharepoint** [comment] 2017-07-22 03:44
can't get **getstorybook** to run on a newly minted mac-mini on a hello-storybook app created to follow these commands

`npm i -g create-react-app getstorybook`
`create-react-app hello-react`
`cd hello-react`
`getstorybook`

everything runs except the getstorybook line and there are no errors anywhere!

I installed the app with both yarn and npm 5.3.0

**Comment by marcelorl** [comment] 2017-09-20 15:37
@dcu-sharepoint the name of the package is `@storybook/cli` then it enables this `getstorybook` command for you.
