### ISSUE TITLE
Feature: Remember hidden action panel

### ISSUE THREAD

**Issue by isuvorov** [kadirahq/react-storybook#200] opened 2016-05-17 11:01 UTC
Case:
1. Open storybook
2. ⌘ ⇧ D
3. F5

**Comment by timkindberg** [comment] 2016-06-18 23:10
Duplicate of #180. Should close.

**Comment by arunoda** [comment] 2016-06-19 05:12
@timkindberg yep. Thanks.

**Closed by arunoda** 2016-06-19 05:12 UTC
Labels: feature
