### ISSUE TITLE
Recursive reference between functions cause "maximum call stack size exceeded"

### ISSUE THREAD

**Issue by guy-kdm** [kadirahq/react-storybook#558] opened 2016-10-22 13:50 UTC
tl;dr - I suppose it's the hot reloading, is there a way to turn it off? 
If I include the following function: 

> function Hi() {
>     function Yo() {
>         return Hi()
>     }
>     return null
> }

I get "maximum call stack size exceeded" on build. 
Is there any way around it?

**Comment by DimitryKislichenko** [comment] 2016-10-23 01:39
Since the last update I've made today to version 2.25.0, start getting same error message for component which worked fine before.

**Comment by arunoda** [comment] 2016-10-23 03:28
It's a bug and on it.

**Comment by arunoda** [comment] 2016-10-23 03:39
@DimitryKislichenko could you send me a sample code as well.

**Comment by arunoda** [comment] 2016-10-23 04:30
Guys, could you check the latest version of storybook where I did a fix.

**Comment by DimitryKislichenko** [comment] 2016-10-23 10:33
Thanks @arunoda, I can confirm that version 2.25.1 works.

**Comment by guy-kdm** [comment] 2016-10-25 10:42
Joining the confirmation just to thank @arunoda for his lightning fast fix.

**Comment by arunoda** [comment] 2016-10-25 11:02
Awesome. So, I'm gonna close this.

**Closed by arunoda** 2016-10-25 11:02 UTC
Labels: bug
