### ISSUE TITLE
Uncaught Error: Cannot find module 'crypto'

### ISSUE THREAD

**Issue by gsabran** [kadirahq/react-storybook#120] opened 2016-04-19 00:19 UTC
The requirement of `uuid` ([here](https://github.com/kadirahq/react-storybook/blob/master/src/client/synced_store.js#L4)) that in turns requires `crypto` ([here](https://github.com/defunctzombie/node-uuid/blob/master/rng.js#L1)) makes my app crash with `Uncaught Error: Cannot find module 'crypto'`

That's weird because `crypto` comes with node. If it's not related to `react-storybook` in particular, feel free to close the issue.

**Comment by arunoda** [comment] 2016-04-19 00:28
Is this a Meteor app? 
When you are getting this error?
Try to provide some way we can reproduce this.

**Comment by gsabran** [comment] 2016-04-19 00:32
Sure. Yes a Meteor app. adding `import { storiesOf, action } from '@kadira/storybook';` in a client file is enough to trigger the require chain and to make the app crash (I just get a blank page)

**Comment by gsabran** [comment] 2016-04-19 00:33
I'll try to get a small example to reproduce the error

**Comment by arunoda** [comment] 2016-04-19 02:59
Okay looking forward to that. Make sure to put stories in a place where Meteor does not load those files.

**Comment by arunoda** [comment] 2016-08-03 03:10
Closing this and adding a ref to here: https://github.com/kadirahq/getstorybook/issues/1
Because, we'll focus efforts on great Meteor support there.

**Closed by arunoda** 2016-08-03 03:10 UTC
Labels: discuss

**Comment by manuelro** [comment] 2017-03-12 20:05
Same problem here while trying to use Cloudinary's npm package. 

`meteor npm install cloudinary --save`
