### ISSUE TITLE
Upgrade to React@15.0.0

### ISSUE THREAD

**Issue by antoinerey** [kadirahq/react-storybook#89] opened 2016-04-08 13:13 UTC
[React@15.0.0 is now out](https://facebook.github.io/react/blog/2016/04/07/react-v15.html). Could the peerDependencies be upgraded to reflect this ?

**Comment by karlguillotte** [comment] 2016-04-08 18:07
@antoinerey Is React 15 working with Storybook for you? 

I am getting: Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `bound `.

Thanks!

**Comment by antoinerey** [comment] 2016-04-08 19:44
Yup. It works the same with both React 14 and 15. The only warning I have is the one about CSS unitless string value. See #84 

PS: I'm using the Storybook 1.6.0

**Comment by karlguillotte** [comment] 2016-04-08 21:00
Thanks @antoinerey! Discovered that the issue is related with recompose.

**Comment by arunoda** [comment] 2016-04-09 12:25
Updated peer-deps to React v15.0.0 and tested.

**Comment by arunoda** [comment] 2016-04-09 12:25
Hope we can close this.

**Closed by arunoda** 2016-04-09 12:25 UTC
