### ISSUE TITLE
Getting 404 Registry returned when trying to run `npm install`

### ISSUE THREAD

**Issue by tedlin182** [kadirahq/react-storybook#15] opened 2016-04-01 16:53 UTC
Simply cloned your repo and ran `npm install` and got the error:
```
npm ERR! 404 Registry returned 404 for GET on https://npm-proxy.fury.io/C__hqNZ_HngaWmEnB-ps/massdrop/@kadira%2fstorybook
npm ERR! 404
npm ERR! 404 '@kadira/storybook' is not in the npm registry.
```

**Comment by luandro** [comment] 2016-04-01 16:57
Same

**Comment by arunoda** [comment] 2016-04-01 17:23
This is a scoped NPM package. I hope that's not available on mirrors yet or something.

**Comment by arunoda** [comment] 2016-04-01 17:24
Is it possible for you guys to use the official mirror. If not directly install from github.

**Comment by tedlin182** [comment] 2016-04-01 18:12
@arunoda - Sorry, mind if you explain more of what you mean?

**Comment by arunoda** [comment] 2016-04-01 23:08
@tedlin182 it seems like you are using fury.io as the NPM mirror. 
May be to support private modules. 

They seems not support scoped NPM modules. Starting with @. 

Just contact them and verify. 
As a quick fix, use our github repo URL as the package version. Then it get the module via NPM.

**Comment by luandro** [comment] 2016-04-02 01:11
Yea, I was using [sinopia](https://www.npmjs.com/package/sinopia). Doing a `npm set registry https://registry.npmjs.org/` solved the problem.

**Comment by arunoda** [comment] 2016-04-02 14:27
I hope we are good here. Hope there's nothing we can do for this.
I'll add this into the README, if someone got this error.

**Comment by arunoda** [comment] 2016-04-02 23:33
It's great to reopen and this this on the issue list.

**Comment by robin-drexler** [comment] 2016-04-03 14:20
Setting the registry, unfortunately doesn't fix it for me. :(

```
~/Development/   master  npm set registry https://registry.npmjs.org/
 ~/Development/   master  npm i --save-dev @kadira/storybook
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "@kadira/storybook"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3

npm ERR! Invalid name: "@kadira/storybook"
```

Also adding the github url in `package.json` leads to the same result.

`"@kadira/storybook": "https://github.com/kadirahq/react-storybook.git#v1.1.0"`

I suppose, I'm still somehow holding it wrong.

**Comment by nrempel** [comment] 2016-04-05 16:45
Has this issue been fixed? I'm having the same issue as @robin-drexler

**Comment by arunoda** [comment] 2016-04-05 22:32
@nrempel @robin-drexler 

You you can get if from the github like this:

```
"@kadira/storybook": "https://github.com/kadirahq/react-storybook.git"
```

I had to publish the `dist` directory to github in order to enable this.

**Comment by nrempel** [comment] 2016-04-06 20:43
Thanks @arunoda.

That didn't fix my problem but I was able to fix it by explicitly upgrading npm to version `3.8.6` by running `npm update npm -g`. Now I can install it correctly with `npm i --save-dev @kadira/storybook`.

I think it was a bug with npm itself.

**Comment by agilliland** [comment] 2016-04-20 17:34
For folks that are on npm 2.x I ran into this issue and found that npm `2.15.1` will fail but after upgrading to `2.15.3` everything is working.

**Comment by tomitrescak** [comment] 2016-06-15 23:07
Would you consider to publish this as non scoped package?
With the scoped name I cannot use the [amazing pnpm substitute of npm project](https://medium.com/@tomi.trescak/reducing-size-of-npm-based-projects-1b02ebe32d61#.1n1vvwto6) that saves soo much space with creating symlinks instead of having a copy of storybook in each project.

I have 13 packages that use storybook. Each package copies over 500MB and 300.000+ files just because of the storybook. This is hell for the cloud backup and more. Thanks!

**Comment by arunoda** [comment] 2016-06-16 02:05
We choose scoped packages for a reason to avoid global name collision (ref: the left-pad story). So, we are unlikely to change that.

But, we do realize the pain.

**Comment by oskarhane** [comment] 2016-08-02 18:51
Im having the `Invalid name: "@kadira/storybook"` issue. 
Same error when I `npm i --save-dev @kadira/storybook` or just add it to package.json with `"@kadira/storybook": "https://github.com/kadirahq/react-storybook.git"`.

I've tried with node 5.11.1 (npm 3.8.6) and 6.2.2 (npm 3.9.5).
The registry I use is `https://registry.npmjs.org/`.

On OS X.

I don't think it's a duplicate of this issue, but issues like https://github.com/kadirahq/react-storybook/issues/22 is referring to this one.

Any ideas?

**Comment by arunoda** [comment] 2016-08-03 00:40
Seems like something like this: https://github.com/npm/npm/issues/10344
This will tell me to move this package to something like `react-storybook`.

**Comment by arunoda** [comment] 2016-09-15 06:49
There's nothing we can do about this issue.

**Closed** 2016-09-15 06:48 UTC

**Comment by gthomas-appfolio** [comment] 2016-09-22 23:05
This is a problem for companies that must use private npm proxies, we can't just switch to using global.  If there isn't a specific reason for using scopes would appreciate you publishing non-scoped.

**Comment by arunoda** [comment] 2016-09-23 00:03
Hey, most of the private repositories now supports scoped modules. 

Try their docs.

**Comment by arunoda** [comment] 2016-09-23 00:04
Check this issue as well: https://github.com/kadirahq/react-storybook/issues/122

**Comment by gthomas-appfolio** [comment] 2016-09-23 15:49
Great, thank you.   This helped: 

> The solution is to set a registry for modules of specific scope. You can add the following to your project's .npmrc file
>
> @kadira:registry=https://registry.npmjs.org

**Comment by ufukomer** [comment] 2016-10-06 14:02
Put your auth token into local .npmrc (the .nprc file inside the repository folder), not into the global one.

```ssh
//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000
```

**Comment by augbog** [comment] 2016-12-07 23:01
@gthomas-appfolio that did the trick for me thanks a lot <3

**Comment by VamsiKonanki** [comment] 2017-03-10 08:57
First Run:

    npm cache clean

Next:

    npm rebuild


Cheers!

**Comment by anhdn** [comment] 2017-06-14 05:39
> You can override the registry for specific scopes, if that's the easiest workaround. For example:
> 
> npm config set @types:registry https://registry.npmjs.org/
> 
> 
> That would tell npm to always get anything for the @types scope directly from the official server on the internet, bypassing Sinopia entirely. Obviously it won't be the right fix for everyone. npm would need internet access (via a proxy if necessary) and there won't be any centralised caching.

**Comment by mbraint** [comment] 2017-06-29 11:32
Also, name in pakage.json , should have scope:
`"name": "@scope/name"`
This help me resolve this issues.

**Comment by BYazdaani** [comment] 2017-09-26 21:19
hi
for me npm cache clean
and 
npm rebuild 
worked
thanks

**Comment by adisain** [comment] 2017-11-11 19:40
**Just run either of the below commands in terminal**
```
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
```

**Comment by suhas777** [comment] 2017-12-26 12:51
Initially I tried with "npm set registry https://registry.npmjs.org" (without quotes) and it didnt work. Later I tried with npm set registry https://registry.npmjs.org/ and it worked. "/" MATTERS

**Comment by ndelangen** [comment] 2017-12-28 14:53
Thank you @suhas777 I've updated the first post to match. 👏

**Comment by IgnacioHR** [comment] 2018-01-27 13:26
hmm... after updating I could successfully do npm install, but I get the same 404 error when I run npm update. Any idea?

**Comment by b1ueRa1n** [comment] 2018-03-15 17:55
@arunoda  Thank you very much!   You are right, I am use the official mirror.
