### ISSUE TITLE
Does it support .jsx file?

### ISSUE THREAD

**Issue by jiji262** [kadirahq/react-storybook#92] opened 2016-04-11 09:18 UTC
Does it support .jsx file?

**Comment by arunoda** [comment] 2016-04-11 09:38
Yes it is. Do you found any issues with that?

**Comment by jiji262** [comment] 2016-04-11 09:53
Yes, with .jsx component, we get a error message:
Error: Cannot find module "../XXX"
(../XXX.jsx is the component)

**Comment by arunoda** [comment] 2016-04-11 09:58
That's pretty weird. 
Make sure you've the latest version of `@kadira/storybook`. (currently `v1.9.0`)

If it's the latest, could you send us a sample repo where we can reproduce it locally.

**Comment by jiji262** [comment] 2016-04-12 05:28
Hi,

I forked the demo codes here: https://github.com/jiji262/react-storybook-simple-demo

I have a demo file for jsx: react-storybook-simple-demo/blob/master/TreeView.jsx

And add this component in story script react-storybook-simple-demo/components/stories/button.js:
import Tree from '../TreeView';

Then the error is:

> Error: Cannot find module "../TreeView"
> webpackMissingModule
> webpack:///components/stories/button.js:2:81
> Object.eval
> webpack:///components/stories/button.js:2:169
> eval
> webpack:///components/stories/button.js:2210:2
> Object.<anonymous>
> webpack:///components/stories/button.js?5cf9:2210:2
> __webpack_require__
> http://localhost:9001/static/preview.bundle.js:556:30
> fn
> http://localhost:9001/static/preview.bundle.js:87:20
> loadStories
> http://localhost:9001/static/preview.bundle.js:2204:2
> ConfigApi._renderMain
> http://localhost:9001/static/preview.bundle.js:1433:2
> render
> http://localhost:9001/static/preview.bundle.js:1433:2
> ConfigApi.configure
> http://localhost:9001/static/preview.bundle.js:1433:2
> ERROR in ./components/stories/button.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ../TreeView in D:\\storybook\components\stories
> resolve file
>   D:\\storybook\components\TreeView doesn't exist
>   D:\\storybook\components\TreeView.webpack.js doesn't exist
>   D:\\storybook\components\TreeView.web.js doesn't exist
>   D:\\storybook\components\TreeView.js doesn't exist
>   D:\\storybook\components\TreeView.json doesn't exist
> resolve directory
>   D:\\storybook\components\TreeView doesn't exist (directory default file)
>   D:\\storybook\components\TreeView\package.json doesn't exist (directory description file)
> [D:\\storybook\components\TreeView]
> [D:\\storybook\components\TreeView.webpack.js]
> [D:\\storybook\components\TreeView.web.js]
> [D:\\storybook\components\TreeView.js]
> [D:\\storybook\components\TreeView.json]
>  @ ./components/stories/button.js 7:16-38

**Comment by wwfalcon** [comment] 2016-04-12 06:17
`import Tree from '../TreeView';`
should be:
`import Tree from '../TreeView.jsx';`

**Comment by jiji262** [comment] 2016-04-12 08:17
@wwfalcon : I tried "../../" and it got the same error as before.

**Comment by wwfalcon** [comment] 2016-04-12 09:06
copy your "webpack.config.js" to ".storybook",and add jsx loader:
`
     {
        test: /\.jsx$/,
        loaders: [ 'babel' ],
        exclude: /node_modules/,
        include: __dirname
      },  
`

**Comment by jeef3** [comment] 2016-04-12 09:24
I think the `.jsx` part of the `import` is actually quite important. You can see the list of files it's attempting to match and none of those attempts have the `.jsx` extension.

**Comment by evidens** [comment] 2016-04-22 17:50
If you want to resolve `.jsx` without including the extension, you need to ensure you have the correct webpack configuration:
```
{
  // … other webpack.config.js options
  resolve: {
     extensions: ['', '.js', '.jsx'],
     // …
  },
  // …
}
```

Otherwise, webpack will only allow `.js` files without the explicit extension.

**Comment by mikem-mup** [comment] 2016-04-28 01:11
This issue can be closed - it's a confusion about import paths + webpack module `resolve` config. Duplicate of #127.

The issue can probably be avoided in the future by adding the `resolve` config that @evidens offered into the webpack config in [the example repo](https://github.com/kadira-samples/react-storybook-demo)

**Comment by arunoda** [comment] 2016-04-28 03:16
Yes. I think this can be closed.

**Closed by arunoda** 2016-04-28 03:16 UTC
Labels: discuss
